---
- hosts: all
  gather_facts: False
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: True
      changed_when: False

- hosts: redis-nodes
  become: true
  pre_tasks:
    - name: Install required EPEL access for redis packages on CentOS / RedHat.
      yum:
        name: epel-release
    # Required to initialise the cluster - redis-trib is a ruby app
    - name: Install ruby
      yum:
        name: ruby
    - name: Install net-tools for testinfra socket testing.
      yum:
        name: net-tools
  roles:
    - redis/core
    - { role: redis/node, redis_port: 7000 }
    - { role: redis/node, redis_port: 7001 }

- hosts: redis-mgt
  become: true
  pre_tasks:
    - name: Install required EPEL access for redis packages on CentOS / RedHat.
      yum:
        name: epel-release
    # Required to initialise the cluster - redis-trib is a ruby app
    - name: Install ruby
      yum:
        name: ruby
    - name: Install net-tools for testinfra socket testing.
      yum:
        name: net-tools

  roles:
    - { role: redis/cluster, redis_cluster_replicas: 1, redis_node_list: "{{ groups['redis-nodes'] | map('extract', hostvars, ['ansible_eth1', 'ipv4', 'address']) | arraypermute( [':'] ) | arraypermute( [7000,7001] ) | list }}" }
