---
# The core package will install evrything required on a server to setup one
# or multiplle redis nodes.
#
# tasks file for redis
- name: Install redis packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ redis_packages }}"

# Simple check - these are done by the package installation
- name: Validate data dir exists
  file:
    path: "{{ redis_data_dir }}"
    state: directory
    owner: redis
    group: redis
    mode: 0755

- name: Validate that log directory exists
  file:
    path: "{{ redis_log_dir }}"
    state: directory
    owner: redis
    group: redis
    mode: 0755

- name: Validate that run directory exists
  file:
    path: "{{ redis_run_dir }}"
    state: directory
    owner: redis
    group: redis
    mode: 0755

# Required for selinux changes
# Add the ports to SELINUX context redis_t (port + cluster port)
- name: Install selinux policy support packages
  package:
    name: policycoreutils-python

# The following tasks are used to install redis cluster management software
#
- name: Install redis gem
  package:
    name: rubygem-redis

- name: Install redis-trib from localfile.
  copy:
    src: redis-trib
    dest: /usr/bin/redis-trib
    mode: 0755

# - name: Create all the nodes.
#   include_role:
#     name: redis/node
#     allow_duplicates: False
#   vars:
#     redis_port: "{{ item }}"
#   with_items:
#     - "{{ redis_ports }}"
