---
dependency:
  name: galaxy
driver:
  name: vagrant
lint:
  name: ansible-lint
platforms:
  - name: redis
    box: centos/7
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
