---
dependency:
  name: galaxy
driver:
  name: vagrant
lint:
  name: yamllint
  enabled: false
platforms:
  - name: redis-1
    groups:
    - redis-nodes
    - redis-mgt
    box: centos/7
    memory: 2048
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
  - name: redis-2
    groups:
    - redis-nodes
    box: centos/7
    memory: 2048
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
  - name: redis-3
    groups:
    - redis-nodes
    box: centos/7
    memory: 2048
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
provisioner:
  name: ansible
  playbooks:
    setup: ../common/create.yml
    teardown: ../common/destroy.yml
    converge: playbook.yml
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
