---
# The following tasks are used to install redis cluster management software
#
- name: Install redis gem
  package:
    name: rubygem-redis

- name: Install redis-trib from localfile.
  copy:
    src: redis-trib
    dest: /usr/bin/redis-trib
    mode: 0755
