---
# tasks file for redis
# Prepare the nodes
- name: Create the node data sub-directory
  file:
    path: "{{ redis_data_dir }}/{{ redis_port }}"
    state: directory
    owner: redis
    group: redis

- name: Create the cluster node redis.conf
  template:
    src: "redis.conf.j2"
    dest: "/etc/redis_{{ redis_port }}.conf"

- name: Create the node redis service file
  template:
    src: "redis.service.j2"
    dest: "/usr/lib/systemd/system/redis_{{ redis_port }}.service"

# Add the ports to SELINUX context redis_t (port + cluster port)
- name: Add ports to SELinux cotext redis_t ( port, cluster port )
  seport:
    ports: "{{ redis_port }},{{ redis_port + 10000 }}"
    proto: tcp
    setype: redis_port_t
    state: present
  when: ansible_os_family == "RedHat"

- name: start and enable the redis node.
  service:
    name: redis_{{ redis_port }}
    state: started
    enabled: yes

# Test that all nodes are up
# Cluster them.
