---
- hosts: all
  gather_facts: 'no'
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: 'yes'
      changed_when: false

- hosts: all
  become: true
  pre_tasks:
    - name: Install required EPEL access for redis packages on CentOS / RedHat.
      yum:
        name: epel-release
    # Required to initialise the cluster - redis-trib is a ruby app
    - name: Install ruby
      package:
        name: ruby
    - name: Install net-tools for testinfra socket testing.
      package:
        name: net-tools
  roles:
    - redis/core
    - redis/node

- hosts: redis-mgt
  become: true
  pre_tasks:
    - name: Install required EPEL access for redis packages on CentOS / RedHat.
      yum:
        name: epel-release
    # Required to initialise the cluster - redis-trib is a ruby app
    - name: Install ruby
      yum:
        name: ruby
    - name: Install net-tools for testinfra socket testing.
      yum:
        name: net-tools
  roles:
    - redis/cluster

- hosts: all
  become: true
  roles:
    - { role: redis/node, redis_state: stop }
